import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowLeft, CheckCircle2, ChevronLeft, ChevronRight, Search, ShieldCheck, ShieldOff } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { EmptyState, ErrorNotice, MetricCard, PageHeader, SortableHeader } from '../components/Ui'
import { SystemVariablesCrud } from '../components/admin/SystemVariablesCrud'
import { api, jsonBody } from '../lib/api'
import { formatDate, formatMonth } from '../lib/format'
import { useSortableData } from '../lib/sorting'

type Tab='resumo'|'usuarios'|'projetos'|'planos'|'auditoria'|'variaveis'|'sistema'
type Summary={totais:{usuarios:number;projetos:number;convites_pendentes:number;participacoes:number};usuariosPorMes:{mes:string;total:number}[];projetosPorMes:{mes:string;total:number}[]}
type User={id:number;nome:string;email:string;plano:string;projetos_proprios:number;participacoes:number;administrador_sistema:boolean;ultimo_acesso_em:string;criado_em:string}
type Project={id:number;nome:string;cidade:string|null;estado:string|null;proprietario:string;email:string;membros:number;criado_em:string}
type Audit={id:number;acao:string;entidade:string;registro_id:number|null;usuario:string|null;projeto:string|null;criado_em:string}
type Plan={id:number;codigo:string;nome:string;limite_projetos_proprios:number|null;ativo:boolean;usuarios:number}
type SystemStatus={api:string;banco:string;dataBanco:string;versaoBanco:string;migrationsAplicadas:number;node:string}

function Pager({page,total,pageSize,onChange}:{page:number;total:number;pageSize:number;onChange:(page:number)=>void}){const pages=Math.max(1,Math.ceil(total/pageSize));if(pages<=1)return null;return <nav className="pager" aria-label="Paginação"><button disabled={page<=1} onClick={()=>onChange(page-1)}><ChevronLeft/>Anterior</button><span>Página <strong>{page}</strong> de {pages}</span><button disabled={page>=pages} onClick={()=>onChange(page+1)}>Próxima<ChevronRight/></button></nav>}

export function AdminPage(){
  const client=useQueryClient();const[tab,setTab]=useState<Tab>('variaveis');const[search,setSearch]=useState('');const[page,setPage]=useState(1);const pageSize=15
  const summary=useQuery({queryKey:['admin-resumo'],queryFn:()=>api<Summary>('/admin/resumo')})
  const users=useQuery({queryKey:['admin-usuarios',page,search],queryFn:()=>api<{usuarios:User[];total:number}>(`/admin/usuarios?pagina=${page}&porPagina=${pageSize}&busca=${encodeURIComponent(search)}`),enabled:tab==='usuarios'})
  const projects=useQuery({queryKey:['admin-projetos',page],queryFn:()=>api<{projetos:Project[];total:number}>(`/admin/projetos?pagina=${page}&porPagina=${pageSize}`),enabled:tab==='projetos'})
  const audit=useQuery({queryKey:['admin-auditoria',page],queryFn:()=>api<{registros:Audit[]}>(`/admin/auditoria?pagina=${page}&porPagina=${pageSize}`),enabled:tab==='auditoria'})
  const plans=useQuery({queryKey:['admin-planos'],queryFn:()=>api<{planos:Plan[]}>('/admin/planos'),enabled:tab==='planos'})
  const status=useQuery({queryKey:['admin-status'],queryFn:()=>api<SystemStatus>('/admin/status'),enabled:tab==='sistema'})
  const userSort=useSortableData(users.data?.usuarios||[],'nome')
  const projectSort=useSortableData(projects.data?.projetos||[],'nome')
  const auditSort=useSortableData(audit.data?.registros||[],'criado_em','desc')
  const adminPermission=useMutation({mutationFn:({id,administrador}:{id:number;administrador:boolean})=>api(`/admin/usuarios/${id}/administrador`,{method:'PATCH',...jsonBody({administrador})}),onSuccess:()=>void client.invalidateQueries({queryKey:['admin-usuarios']})})
  const changeTab=(next:Tab)=>{setTab(next);setPage(1);setSearch('')}
  const error=summary.error||users.error||projects.error||audit.error||plans.error||status.error||adminPermission.error
  const chart=summary.data?.usuariosPorMes.map(item=>({...item,label:formatMonth(item.mes)}))||[]
  return <div className="admin-page"><header className="admin-header"><a className="brand dark" href="/"><span className="brand-mark">M</span><span>MinhaObra</span></a><Link to="/app"><ArrowLeft/>Voltar aos projetos</Link></header><main><PageHeader eyebrow="ADMINISTRAÇÃO GERAL" title="Gestão da plataforma" description="Uma visão independente das permissões e propriedades de cada obra."/><nav className="admin-tabs">{([['resumo','Resumo'],['usuarios','Usuários'],['projetos','Projetos'],['planos','Planos'],['auditoria','Auditoria'],['variaveis','Variáveis do Sistema'],['sistema','Sistema']] as [Tab,string][]).map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>changeTab(key)}>{label}</button>)}</nav>{error&&<ErrorNotice message={error.message}/>}
    {tab==='resumo'&&summary.data&&<><section className="metrics-row"><MetricCard label="Usuários ativos" value={summary.data.totais.usuarios}/><MetricCard label="Obras ativas" value={summary.data.totais.projetos}/><MetricCard label="Participações" value={summary.data.totais.participacoes}/><MetricCard label="Convites pendentes" value={summary.data.totais.convites_pendentes}/></section><section className="dashboard-panel admin-growth"><header><div><span>CRESCIMENTO</span><h2>Novos usuários por mês</h2></div></header><ResponsiveContainer width="100%" height={280}><LineChart data={chart}><CartesianGrid vertical={false} stroke="#e5e2da"/><XAxis dataKey="label" axisLine={false} tickLine={false}/><YAxis allowDecimals={false} axisLine={false} tickLine={false}/><Tooltip/><Line dataKey="total" name="Usuários" stroke="#836d53" strokeWidth={3}/></LineChart></ResponsiveContainer></section></>}
    {tab==='usuarios'&&<><div className="table-toolbar"><label className="search-field"><span>Pesquisar usuários</span><div><Search/><input value={search} onChange={event=>{setSearch(event.target.value);setPage(1)}} placeholder="Nome ou e-mail"/></div></label></div><section className="data-table-wrap admin-users"><div className="table-summary"><strong>{users.data?.total||0}</strong> usuários cadastrados</div>{users.data?.usuarios.length?<table className="data-table"><thead><tr><SortableHeader<User> label="Usuário" column="nome" activeColumn={userSort.sort.key} direction={userSort.sort.direction} onSort={userSort.toggle}/><SortableHeader<User> label="Plano" column="plano" activeColumn={userSort.sort.key} direction={userSort.sort.direction} onSort={userSort.toggle}/><SortableHeader<User> label="Projetos próprios" column="projetos_proprios" activeColumn={userSort.sort.key} direction={userSort.sort.direction} onSort={userSort.toggle}/><SortableHeader<User> label="Participações" column="participacoes" activeColumn={userSort.sort.key} direction={userSort.sort.direction} onSort={userSort.toggle}/><SortableHeader<User> label="Último acesso" column="ultimo_acesso_em" activeColumn={userSort.sort.key} direction={userSort.sort.direction} onSort={userSort.toggle}/><SortableHeader<User> label="Administração global" column="administrador_sistema" activeColumn={userSort.sort.key} direction={userSort.sort.direction} onSort={userSort.toggle}/></tr></thead><tbody>{userSort.sorted.map(user=><tr key={user.id}><td><strong>{user.nome}</strong><small>{user.email}</small></td><td>{user.plano}</td><td>{user.projetos_proprios}</td><td>{user.participacoes}</td><td>{formatDate(user.ultimo_acesso_em)}</td><td><button className={`admin-toggle ${user.administrador_sistema?'active':''}`} disabled={adminPermission.isPending} onClick={()=>{const action=user.administrador_sistema?'revogar':'conceder';if(confirm(`Deseja ${action} a permissão administrativa de ${user.nome}?`))adminPermission.mutate({id:user.id,administrador:!user.administrador_sistema})}}>{user.administrador_sistema?<><ShieldCheck/>Administrador do Sistema</>:<><ShieldOff/>Conceder</>}</button></td></tr>)}</tbody></table>:<EmptyState title="Nenhum usuário encontrado" description="Ajuste os termos da pesquisa."/>}</section><Pager page={page} total={users.data?.total||0} pageSize={pageSize} onChange={setPage}/></>}
    {tab==='projetos'&&<><section className="data-table-wrap"><div className="table-summary"><strong>{projects.data?.total||0}</strong> projetos ativos</div><table className="data-table"><thead><tr><SortableHeader<Project> label="Projeto" column="nome" activeColumn={projectSort.sort.key} direction={projectSort.sort.direction} onSort={projectSort.toggle}/><SortableHeader<Project> label="Proprietário" column="proprietario" activeColumn={projectSort.sort.key} direction={projectSort.sort.direction} onSort={projectSort.toggle}/><SortableHeader<Project> label="Localidade" column="cidade" activeColumn={projectSort.sort.key} direction={projectSort.sort.direction} onSort={projectSort.toggle}/><SortableHeader<Project> label="Membros" column="membros" activeColumn={projectSort.sort.key} direction={projectSort.sort.direction} onSort={projectSort.toggle}/><SortableHeader<Project> label="Criado em" column="criado_em" activeColumn={projectSort.sort.key} direction={projectSort.sort.direction} onSort={projectSort.toggle}/></tr></thead><tbody>{projectSort.sorted.map(project=><tr key={project.id}><td><strong>{project.nome}</strong></td><td><strong>{project.proprietario}</strong><small>{project.email}</small></td><td>{[project.cidade,project.estado].filter(Boolean).join(' · ')||'—'}</td><td>{project.membros}</td><td>{formatDate(project.criado_em)}</td></tr>)}</tbody></table></section><Pager page={page} total={projects.data?.total||0} pageSize={pageSize} onChange={setPage}/></>}
    {tab==='planos'&&<section className="admin-card-grid">{plans.data?.planos.map(plan=><article key={plan.id}><span>{plan.codigo}</span><h2>{plan.nome}</h2><strong>{plan.usuarios} usuários</strong><p>{plan.limite_projetos_proprios===null?'Projetos próprios ilimitados':`${plan.limite_projetos_proprios} projeto próprio por usuário`}</p><small>{plan.ativo?'Plano ativo':'Plano inativo'}</small></article>)}</section>}
    {tab==='auditoria'&&<section className="data-table-wrap"><div className="table-summary">Atividades mais recentes</div><table className="data-table"><thead><tr><SortableHeader<Audit> label="Data" column="criado_em" activeColumn={auditSort.sort.key} direction={auditSort.sort.direction} onSort={auditSort.toggle}/><SortableHeader<Audit> label="Usuário" column="usuario" activeColumn={auditSort.sort.key} direction={auditSort.sort.direction} onSort={auditSort.toggle}/><SortableHeader<Audit> label="Projeto" column="projeto" activeColumn={auditSort.sort.key} direction={auditSort.sort.direction} onSort={auditSort.toggle}/><SortableHeader<Audit> label="Ação" column="acao" activeColumn={auditSort.sort.key} direction={auditSort.sort.direction} onSort={auditSort.toggle}/><SortableHeader<Audit> label="Entidade" column="entidade" activeColumn={auditSort.sort.key} direction={auditSort.sort.direction} onSort={auditSort.toggle}/><SortableHeader<Audit> label="Registro" column="registro_id" activeColumn={auditSort.sort.key} direction={auditSort.sort.direction} onSort={auditSort.toggle}/></tr></thead><tbody>{auditSort.sorted.map(record=><tr key={record.id}><td>{formatDate(record.criado_em)}</td><td>{record.usuario||'Sistema'}</td><td>{record.projeto||'Global'}</td><td>{record.acao.replaceAll('_',' ')}</td><td>{record.entidade}</td><td>{record.registro_id||'—'}</td></tr>)}</tbody></table></section>}
    {tab==='variaveis'&&<SystemVariablesCrud/>}
    {tab==='sistema'&&status.data&&<section className="system-status"><article><CheckCircle2/><span>API</span><strong>{status.data.api}</strong></article><article><CheckCircle2/><span>PostgreSQL</span><strong>{status.data.banco}</strong></article><article><span>MIGRATIONS</span><strong>{status.data.migrationsAplicadas}</strong><small>aplicadas</small></article><article><span>RUNTIME</span><strong>{status.data.node}</strong><small>{formatDate(status.data.dataBanco)}</small></article><p>{status.data.versaoBanco}</p></section>}
  </main></div>}
