import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Copy, MailPlus, RotateCcw, Shield, Trash2, UserRound, X } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import { useParams } from 'react-router-dom'
import { AddButton, EmptyState, ErrorNotice, PageHeader, SortableHeader } from '../components/Ui'
import { api, jsonBody } from '../lib/api'
import { formatDate } from '../lib/format'
import { roleLabel, useProjectAccess } from '../lib/projectAccess'
import { useSortableData } from '../lib/sorting'

type Permission = { id: number; chave: string; modulo: string; acao: string; descricao: string }
type Member = { id: number; usuario_id: number; nome: string; email: string; foto_url: string | null; papel: 'PROPRIETARIO' | 'ENGENHEIRO' | 'LEITOR'; nome_papel: string; proprietario: boolean; permissoes: Record<string, boolean> }
type Invitation = { id: number; email: string; papel: string; expira_em: string; aceito_em: string | null; cancelado_em: string | null; criado_em: string; situacao?: string }
type CreatedInvite = { link: string; emailEnviado: boolean }

export function MembersPage({ permissionsOnly = false }: { permissionsOnly?: boolean }) {
  const { projetoId } = useParams()
  const { can } = useProjectAccess()
  const client = useQueryClient()
  const endpoint = `/projetos/${projetoId}/membros`
  const [inviteOpen, setInviteOpen] = useState(false)
  const [editing, setEditing] = useState<Member | null>(null)
  const [permissionState, setPermissionState] = useState<Record<string, boolean>>({})
  const [createdInvite, setCreatedInvite] = useState<CreatedInvite | null>(null)
  const invitationStatus = (item: Invitation) => item.aceito_em ? 'Aceito' : item.cancelado_em ? 'Cancelado' : new Date(item.expira_em) < new Date() ? 'Expirado' : 'Pendente'
  const { data, error } = useQuery({ queryKey: ['membros', projetoId], queryFn: () => api<{ membros: Member[]; permissoesDisponiveis: Permission[] }>(endpoint) })
  const { data: invitations } = useQuery({ queryKey: ['convites', projetoId], queryFn: () => api<{ convites: Invitation[] }>(`${endpoint}/convites`), enabled: !permissionsOnly })
  const invitationRows = useMemo(() => (invitations?.convites || []).map(item => ({ ...item, situacao: invitationStatus(item) })), [invitations])
  const invitationSort = useSortableData(invitationRows, 'email')
  const invite = useMutation({ mutationFn: (payload: Record<string, unknown>) => api<{ convite: CreatedInvite }>(`${endpoint}/convites`, { method: 'POST', ...jsonBody(payload) }), onSuccess: result => { setCreatedInvite(result.convite); void client.invalidateQueries({ queryKey: ['convites', projetoId] }) } })
  const cancelInvitation = useMutation({ mutationFn: (id: number) => api(`${endpoint}/convites/${id}`, { method: 'DELETE' }), onSuccess: () => void client.invalidateQueries({ queryKey: ['convites', projetoId] }) })
  const changeRole = useMutation({ mutationFn: ({ id, papel }: { id: number; papel: string }) => api(`${endpoint}/${id}/papel`, { method: 'PUT', ...jsonBody({ papel }) }), onSuccess: () => void client.invalidateQueries({ queryKey: ['membros', projetoId] }) })
  const savePermissions = useMutation({ mutationFn: ({ id, values }: { id: number; values: Record<string, boolean> }) => api(`${endpoint}/${id}/permissoes`, { method: 'PUT', ...jsonBody({ permissoes: Object.entries(values).map(([chave, permitido]) => ({ chave, permitido })) }) }), onSuccess: () => { setEditing(null); void client.invalidateQueries({ queryKey: ['membros', projetoId] }) } })
  const remove = useMutation({ mutationFn: (id: number) => api(`${endpoint}/${id}`, { method: 'DELETE' }), onSuccess: () => void client.invalidateQueries({ queryKey: ['membros', projetoId] }) })
  const groups = useMemo(() => (data?.permissoesDisponiveis || []).reduce<Record<string, Permission[]>>((result, permission) => { (result[permission.modulo] ??= []).push(permission); return result }, {}), [data])
  const openPermissions = (member: Member) => { setEditing(member); setPermissionState(member.permissoes || {}) }
  const submitInvite = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); invite.mutate({ email: form.get('email'), papel: form.get('papel') }) }

  return <div>
    <PageHeader eyebrow="GESTÃO DO PROJETO" title={permissionsOnly ? 'Permissões' : 'Participantes'} description={permissionsOnly ? 'Defina com precisão o que cada participante pode consultar ou alterar.' : 'Convide engenheiros e observadores sem consumir a cota de projetos próprios deles.'} action={!permissionsOnly && can('membros.convidar') ? <AddButton onClick={() => { setInviteOpen(true); setCreatedInvite(null) }}><MailPlus />Convidar</AddButton> : undefined} />
    {error && <ErrorNotice message={error.message} />}
    {!data?.membros.length ? <EmptyState icon={UserRound} title="Nenhum participante" description="O proprietário sempre permanece vinculado à própria obra." /> : <div className="members-list">{data.membros.map(member => <article key={member.id}><div className="member-avatar">{member.foto_url ? <img src={member.foto_url} alt="" referrerPolicy="no-referrer" /> : member.nome.charAt(0)}</div><div><strong>{member.nome}</strong><small>{member.email}</small></div><select value={member.papel} disabled={member.proprietario||!can('membros.atualizar')} onChange={event => changeRole.mutate({ id: member.id, papel: event.target.value })}><option value="PROPRIETARIO">Proprietário</option><option value="ENGENHEIRO">Engenheiro</option><option value="LEITOR">Observador</option></select>{can('membros.atualizar')&&<button className="app-button" disabled={member.proprietario} onClick={() => openPermissions(member)}><Shield />Permissões</button>}{!member.proprietario&&can('membros.excluir')&&<button className="icon-button danger" onClick={() => confirm(`Remover ${member.nome} do projeto?`) && remove.mutate(member.id)}><Trash2 /></button>}</article>)}</div>}
    {!permissionsOnly && <section className="invitations-section"><h2>Convites</h2>{!invitations?.convites.length ? <p>Nenhum convite enviado.</p> : <div className="data-table-wrap"><table className="data-table"><thead><tr><SortableHeader<Invitation> label="E-mail" column="email" activeColumn={invitationSort.sort.key} direction={invitationSort.sort.direction} onSort={invitationSort.toggle}/><SortableHeader<Invitation> label="Papel" column="papel" activeColumn={invitationSort.sort.key} direction={invitationSort.sort.direction} onSort={invitationSort.toggle}/><SortableHeader<Invitation> label="Enviado" column="criado_em" activeColumn={invitationSort.sort.key} direction={invitationSort.sort.direction} onSort={invitationSort.toggle}/><SortableHeader<Invitation> label="Situação" column="situacao" activeColumn={invitationSort.sort.key} direction={invitationSort.sort.direction} onSort={invitationSort.toggle}/><th>Ações</th></tr></thead><tbody>{invitationSort.sorted.map(item => { const status = invitationStatus(item); return <tr key={item.id}><td>{item.email}</td><td>{roleLabel(item.papel)}</td><td>{formatDate(item.criado_em)}</td><td>{status}</td><td>{status === 'Pendente' ? <button className="app-button danger" disabled={cancelInvitation.isPending} onClick={() => confirm(`Cancelar o convite para ${item.email}?`) && cancelInvitation.mutate(item.id)}><Trash2 />Cancelar</button> : '—'}</td></tr> })}</tbody></table></div>}</section>}
    {inviteOpen && <div className="dialog-backdrop"><section className="dialog"><header><div><small>NOVO PARTICIPANTE</small><h2>Enviar convite</h2></div><button onClick={() => setInviteOpen(false)}><X /></button></header>{invite.error && <ErrorNotice message={invite.error.message} />}{createdInvite ? <div className="invitation-result"><strong>Convite criado</strong><p>{createdInvite.emailEnviado ? 'O convite foi enviado por e-mail.' : 'O SMTP não está configurado; copie e compartilhe o link abaixo.'}</p><div><input readOnly value={createdInvite.link} /><button onClick={() => void navigator.clipboard.writeText(createdInvite.link)}><Copy /></button></div><button className="app-button primary" onClick={() => setInviteOpen(false)}>Concluir</button></div> : <form onSubmit={submitInvite}><label className="field span-2"><span>E-mail da conta Google</span><input type="email" name="email" required /></label><label className="field span-2"><span>Papel inicial</span><select name="papel"><option value="ENGENHEIRO">Engenheiro</option><option value="LEITOR">Observador</option></select></label><div className="role-explainer span-2"><RotateCcw /><p>O convite expira em sete dias e só pode ser aceito pela conta Google correspondente.</p></div><footer className="form-actions span-2"><button type="button" className="app-button" onClick={() => setInviteOpen(false)}>Cancelar</button><button className="app-button primary" disabled={invite.isPending}>{invite.isPending ? 'Criando…' : 'Criar convite'}</button></footer></form>}</section></div>}
    {editing && <div className="dialog-backdrop"><section className="dialog large permission-dialog"><header><div><small>ACESSO GRANULAR</small><h2>Permissões de {editing.nome}</h2></div><button onClick={() => setEditing(null)}><X /></button></header><p className="dialog-intro">As alterações são validadas no servidor em cada requisição. O papel define o padrão; esta tela registra as permissões efetivas escolhidas.</p><div className="permission-matrix">{Object.entries(groups).map(([module, permissions]) => <section key={module}><h3>{module}</h3>{permissions?.map(permission => <label key={permission.chave}><input type="checkbox" checked={Boolean(permissionState[permission.chave])} onChange={event => setPermissionState(state => ({ ...state, [permission.chave]: event.target.checked }))} /><span><strong>{permission.acao}</strong><small>{permission.descricao}</small></span></label>)}</section>)}</div><footer className="form-actions"><button className="app-button" onClick={() => setEditing(null)}>Cancelar</button><button className="app-button primary" onClick={() => savePermissions.mutate({ id: editing.id, values: permissionState })}>Salvar permissões</button></footer></section></div>}
  </div>
}
