import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ImagePlus, MapPin, Save, Search, Trash2 } from 'lucide-react'
import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { ProjectLocationMap } from '../components/ProjectLocationMap'
import { ErrorNotice, PageHeader } from '../components/Ui'
import { api, jsonBody } from '../lib/api'
import { useProjectAccess } from '../lib/projectAccess'

type Project = { nome:string;descricao:string;data_inicio:string|null;previsao_termino:string|null;cep:string|null;logradouro:string|null;numero:string|null;complemento:string|null;bairro:string|null;cidade:string|null;estado:string|null;codigo_ibge_cidade:string|null;latitude:string|null;longitude:string|null;area_com_laje:string|null;area_sem_laje:string|null;processo_aprovacao:string|null;pasta_digital:string|null;planta_numero:string|null;alvara:string|null;art:string|null;cno_obra:string|null;matricula_terreno:string|null }
type ProjectResult={projeto:Project;proprietario:boolean}
type ViaCep={erro?:boolean;cep?:string;logradouro?:string;complemento?:string;bairro?:string;localidade?:string;uf?:string;ibge?:string}
type PresentationDocument={id:number;nome_original:string|null}

export function SettingsPage(){
  const{projetoId}=useParams();const navigate=useNavigate();const client=useQueryClient();const formRef=useRef<HTMLFormElement>(null)
  const{can}=useProjectAccess()
  const[success,setSuccess]=useState('');const[cepStatus,setCepStatus]=useState('');const[searchingCep,setSearchingCep]=useState(false)
  const[periodError,setPeriodError]=useState('');const[periodStart,setPeriodStart]=useState('');const[periodEnd,setPeriodEnd]=useState('')
  const[latitude,setLatitude]=useState<number|null>(null);const[longitude,setLongitude]=useState<number|null>(null);const[areaComLaje,setAreaComLaje]=useState(0);const[areaSemLaje,setAreaSemLaje]=useState(0)
  const{data,error}=useQuery({queryKey:['configuracoes-projeto',projetoId],queryFn:()=>api<ProjectResult>(`/projetos/${projetoId}/configuracoes`)})
  const presentation=useQuery({queryKey:['imagem-apresentacao',projetoId],queryFn:()=>api<{documento:PresentationDocument|null}>(`/projetos/${projetoId}/acervo/documentos/apresentacao`)})
  // Sincroniza uma única carga remota com os controles interativos do mapa e das áreas.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{if(data){setLatitude(data.projeto.latitude===null?null:Number(data.projeto.latitude));setLongitude(data.projeto.longitude===null?null:Number(data.projeto.longitude));setAreaComLaje(Number(data.projeto.area_com_laje||0));setAreaSemLaje(Number(data.projeto.area_sem_laje||0));setPeriodStart(data.projeto.data_inicio?.slice(0,10)||'');setPeriodEnd(data.projeto.previsao_termino?.slice(0,10)||'')}},[data])
  const updateLocation=useCallback((lat:number,lng:number)=>{setLatitude(Number(lat.toFixed(7)));setLongitude(Number(lng.toFixed(7)))},[])
  const save=useMutation({mutationFn:(payload:Record<string,unknown>)=>api(`/projetos/${projetoId}/configuracoes`,{method:'PUT',...jsonBody(payload)}),onSuccess:()=>{setSuccess('Dados da obra atualizados.');void client.invalidateQueries({queryKey:['configuracoes-projeto',projetoId]});void client.invalidateQueries({queryKey:['projeto',projetoId]});void client.invalidateQueries({queryKey:['projetos']});void client.invalidateQueries({queryKey:['dashboard',projetoId]})}})
  const remove=useMutation({mutationFn:()=>api(`/projetos/${projetoId}`,{method:'DELETE'}),onSuccess:()=>navigate('/app')})
  const savePresentation=useMutation({mutationFn:(form:FormData)=>api(`/projetos/${projetoId}/acervo/documentos/apresentacao`,{method:'POST',body:form}),onSuccess:()=>{void client.invalidateQueries({queryKey:['imagem-apresentacao',projetoId]});void client.invalidateQueries({queryKey:['documentos',projetoId]});void client.invalidateQueries({queryKey:['projetos']})}})
  const field=(name:string)=>formRef.current?.elements.namedItem(name) as HTMLInputElement|null
  const buscarCep=async()=>{const numeros=String(field('cep')?.value||'').replace(/\D/g,'');if(!/^\d{8}$/.test(numeros)){setCepStatus('Informe um CEP com 8 dígitos.');return}setSearchingCep(true);setCepStatus('Consultando o CEP…');try{const response=await fetch(`https://viacep.com.br/ws/${numeros}/json/`);if(!response.ok)throw new Error('Não foi possível consultar o CEP.');const address=await response.json() as ViaCep;if(address.erro)throw new Error('CEP não encontrado.');const values:Record<string,string>={cep:address.cep||numeros,logradouro:address.logradouro||'',complemento:address.complemento||'',bairro:address.bairro||'',cidade:address.localidade||'',estado:address.uf||'',codigoIbgeCidade:address.ibge||''};Object.entries(values).forEach(([name,value])=>{const input=field(name);if(input)input.value=value.toUpperCase()});setCepStatus('Endereço localizado. Ajuste o marcador para a posição exata.');const query=[values.logradouro,values.cidade,values.estado,'Brasil'].filter(Boolean).join(', ');const geoResponse=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=br&q=${encodeURIComponent(query)}`);if(geoResponse.ok){const places=await geoResponse.json() as {lat:string;lon:string}[];if(places[0])updateLocation(Number(places[0].lat),Number(places[0].lon))}}catch(reason){setCepStatus(`${reason instanceof Error?reason.message:'Falha na consulta.'} Preencha o endereço manualmente.`)}finally{setSearchingCep(false)}}
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setSuccess('');setPeriodError('');if(periodStart&&periodEnd&&periodEnd<periodStart){setPeriodError('A previsão de fim não pode ser anterior à previsão de início.');return}const form=new FormData(event.currentTarget);const value=(name:string)=>form.get(name)||null;save.mutate({nome:value('nome'),descricao:value('descricao'),dataInicio:periodStart||null,previsaoTermino:periodEnd||null,cep:value('cep'),logradouro:value('logradouro'),numero:value('numero'),complemento:value('complemento'),bairro:value('bairro'),cidade:value('cidade'),estado:value('estado'),codigoIbgeCidade:value('codigoIbgeCidade'),latitude,longitude,areaComLaje:value('areaComLaje'),areaSemLaje:value('areaSemLaje'),processoAprovacao:value('processoAprovacao'),pastaDigital:value('pastaDigital'),plantaNumero:value('plantaNumero'),alvara:value('alvara'),art:value('art'),cnoObra:value('cnoObra'),matriculaTerreno:value('matriculaTerreno')})}
  return <div><PageHeader eyebrow="GESTÃO" title="Configurações da obra" description="Dados gerais, endereço, localização e registros técnicos organizados por grupo."/>{(error||save.error||remove.error)&&<ErrorNotice message={(error||save.error||remove.error)!.message}/>} {periodError&&<ErrorNotice message={periodError}/>} {success&&<div className="success-notice">{success}</div>}{data&&<section className="settings-panel expanded"><form ref={formRef} onSubmit={submit}>
    <fieldset className="settings-group"><legend>Identificação</legend><label className="field span-2"><span>Nome do projeto</span><input name="nome" required defaultValue={data.projeto.nome}/></label><div className="identification-content span-2"><label className="field"><span>Descrição</span><textarea name="descricao" required rows={4} defaultValue={data.projeto.descricao}/></label><div className="presentation-image"><div><span>Imagem de apresentação</span><small>Usada na caixa de apresentação do projeto e mantida em Documentos.</small></div>{presentation.data?.documento?<img src={`/api/projetos/${projetoId}/acervo/documentos/${presentation.data.documento.id}/arquivo`} alt="Imagem de apresentação do projeto"/>:<div className="presentation-placeholder"><ImagePlus/></div>}<label className="app-button"><ImagePlus/>{savePresentation.isPending?'Enviando…':'Enviar imagem'}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={savePresentation.isPending} onChange={event=>{const file=event.target.files?.[0];if(!file)return;const form=new FormData();form.set('arquivo',file);savePresentation.mutate(form);event.currentTarget.value=''}}/></label>{savePresentation.error&&<ErrorNotice message={savePresentation.error.message}/>}</div></div></fieldset>
    <fieldset className="settings-group"><legend>Período previsto da obra</legend><label className="field"><span>Previsão de início</span><input name="dataInicio" type="date" value={periodStart} max={periodEnd||undefined} onChange={event=>{setPeriodStart(event.target.value);setPeriodError('')}}/></label><label className="field"><span>Previsão de fim</span><input name="previsaoTermino" type="date" value={periodEnd} min={periodStart||undefined} onChange={event=>{setPeriodEnd(event.target.value);setPeriodError('')}}/></label></fieldset>
    <fieldset className="settings-group"><legend>Endereço da obra</legend><div className="cep-row"><label className="field"><span>CEP</span><input name="cep" defaultValue={data.projeto.cep||''} placeholder="00000-000"/></label><button type="button" className="app-button dark" disabled={searchingCep} onClick={()=>void buscarCep()}><Search/>{searchingCep?'Buscando…':'Buscar CEP'}</button><small>{cepStatus}</small></div><label className="field span-2"><span>Logradouro</span><input name="logradouro" defaultValue={data.projeto.logradouro||''}/></label><label className="field"><span>Número</span><input name="numero" defaultValue={data.projeto.numero||''}/></label><label className="field"><span>Complemento</span><input name="complemento" defaultValue={data.projeto.complemento||''}/></label><label className="field"><span>Bairro</span><input name="bairro" defaultValue={data.projeto.bairro||''}/></label><label className="field"><span>Cidade</span><input name="cidade" defaultValue={data.projeto.cidade||''}/></label><label className="field small-field"><span>Estado</span><input name="estado" maxLength={2} defaultValue={data.projeto.estado||''}/></label><input type="hidden" name="codigoIbgeCidade" defaultValue={data.projeto.codigo_ibge_cidade||''}/></fieldset>
    <fieldset className="settings-group map-group"><legend>Localização exata</legend><div className="location-coordinates"><label className="field"><span>Latitude</span><input readOnly value={latitude??''}/></label><label className="field"><span>Longitude</span><input readOnly value={longitude??''}/></label><span><MapPin/>Clique no mapa ou arraste o marcador.</span></div><ProjectLocationMap latitude={latitude} longitude={longitude} onChange={updateLocation}/></fieldset>
    <fieldset className="settings-group"><legend>Áreas construídas</legend><label className="field"><span>Área com laje (m²)</span><input type="number" step="0.01" min="0" name="areaComLaje" defaultValue={data.projeto.area_com_laje||''} onChange={event=>setAreaComLaje(Number(event.target.value||0))}/></label><label className="field"><span>Área sem laje (m²)</span><input type="number" step="0.01" min="0" name="areaSemLaje" defaultValue={data.projeto.area_sem_laje||''} onChange={event=>setAreaSemLaje(Number(event.target.value||0))}/></label><div className="area-total span-2"><span>Área total</span><strong>{(areaComLaje+areaSemLaje).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})} m²</strong></div></fieldset>
    <fieldset className="settings-group technical-group"><legend>Documentação técnica</legend><label className="field"><span>Processo de aprovação</span><input name="processoAprovacao" defaultValue={data.projeto.processo_aprovacao||''}/></label><label className="field"><span>Pasta digital</span><input name="pastaDigital" defaultValue={data.projeto.pasta_digital||''}/></label><label className="field"><span>Planta</span><input name="plantaNumero" defaultValue={data.projeto.planta_numero||''}/></label><label className="field"><span>Alvará</span><input name="alvara" defaultValue={data.projeto.alvara||''}/></label><label className="field"><span>ART</span><input name="art" defaultValue={data.projeto.art||''}/></label><label className="field"><span>CNO da obra</span><input name="cnoObra" defaultValue={data.projeto.cno_obra||''}/></label><label className="field span-2"><span>Matrícula do terreno</span><input name="matriculaTerreno" defaultValue={data.projeto.matricula_terreno||''}/></label></fieldset>
    {can('configuracoes.atualizar')&&<footer className="form-actions span-2"><button className="app-button primary" disabled={save.isPending}><Save/> {save.isPending?'Salvando…':'Salvar alterações'}</button></footer>}</form>{data.proprietario&&<aside className="danger-zone"><div><strong>Excluir esta obra</strong><p>O projeto deixa de aparecer para todos os participantes. Os dados permanecem preservados por exclusão lógica.</p></div><button className="app-button danger" onClick={()=>confirm(`Excluir o projeto ${data.projeto.nome}?`)&&remove.mutate()}><Trash2/>Excluir projeto</button></aside>}</section>}</div>
}
