import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ChevronDown, ChevronRight, Pencil, Plus, Trash2, Upload, X } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { useParams } from 'react-router-dom'
import { ImportDialog } from '../components/imports/ImportDialog'
import { ExportAction } from '../components/ExportDialog'
import { AddButton, EmptyState, ErrorNotice, PageHeader, SortableHeader } from '../components/Ui'
import { api, jsonBody } from '../lib/api'
import { formatDate, formatMoney } from '../lib/format'
import { formatStageLabel } from '../lib/stage'
import { useSortableData } from '../lib/sorting'
import { useProjectAccess } from '../lib/projectAccess'

type ScheduleItem={id:number;parent_id:number|null;nome:string;descricao:string|null;cor:string;data_inicio_previsto:string|null;data_fim_previsto:string|null;data_inicio:string|null;data_fim:string|null;valor_previsto:string;valor_pago:string;ordem:number}
type ScheduleStage=ScheduleItem&{subitens:ScheduleItem[]}
type ScheduleResponse={etapas:ScheduleItem[];arvore:ScheduleStage[];total:number;totalRegistros:number}
const EMPTY_SCHEDULE:ScheduleResponse={etapas:[],arvore:[],total:0,totalRegistros:0}

export function StagesPage(){
  const { projetoId }=useParams(); const client=useQueryClient(); const endpoint=`/projetos/${projetoId}/cronograma`
  const {can}=useProjectAccess()
  const [editing,setEditing]=useState<ScheduleItem|'new'|null>(null); const [newParentId,setNewParentId]=useState<number|null>(null)
  const [importing,setImporting]=useState(false); const [expanded,setExpanded]=useState<Set<number>>(new Set()); const [showPlanned,setShowPlanned]=useState(false)
  const { data:response,error }=useQuery({queryKey:['etapas',projetoId],queryFn:()=>api<ScheduleResponse>(endpoint)})
  const data=response??EMPTY_SCHEDULE; const parents=data.arvore; const stagesSort=useSortableData(parents,'ordem')
  const closeEditor=()=>{setEditing(null);setNewParentId(null)}
  const openNewStage=()=>{setNewParentId(null);setEditing('new')}
  const openNewChild=(parentId:number)=>{setNewParentId(parentId);setEditing('new');setExpanded(current=>new Set(current).add(parentId))}
  const openEdit=(item:ScheduleItem)=>{setNewParentId(item.parent_id);setEditing(item)}
  const save=useMutation({mutationFn:({id,payload}:{id?:number;payload:Record<string,unknown>})=>api(`${endpoint}${id?`/${id}`:''}`,{method:id?'PUT':'POST',...jsonBody(payload)}),onSuccess:()=>{closeEditor();void client.invalidateQueries({queryKey:['etapas',projetoId]});void client.invalidateQueries({queryKey:['dashboard',projetoId]})}})
  const remove=useMutation({mutationFn:(id:number)=>api(`${endpoint}/${id}`,{method:'DELETE'}),onSuccess:()=>{void client.invalidateQueries({queryKey:['etapas',projetoId]});void client.invalidateQueries({queryKey:['dashboard',projetoId]})}})
  const isChild=editing==='new'?Boolean(newParentId):Boolean(editing?.parent_id)
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const parentId=editing==='new'?newParentId:editing?.parent_id;save.mutate({id:editing==='new'?undefined:editing?.id,payload:{parent_id:parentId,nome:form.get('nome'),descricao:form.get('descricao')||null,data_inicio_previsto:form.get('data_inicio_previsto')||null,data_fim_previsto:form.get('data_fim_previsto')||null,data_inicio:form.get('data_inicio')||null,data_fim:form.get('data_fim')||null,valor_previsto:form.get('valor_previsto')||0,ordem:form.get('ordem')||0}})}
  const toggle=(id:number)=>setExpanded(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next})
  return <div>
    <PageHeader eyebrow="PLANEJAMENTO" title="Cronograma da obra" description="Etapas, subitens, valores previstos e pagamentos consolidados automaticamente." action={<div className="heading-actions">{can('etapas.exportar')&&<ExportAction title="Cronograma" pdfUrl={`/api${endpoint}/relatorio.pdf`} xlsxUrl={`/api${endpoint}/relatorio.xlsx`}/>} {can('etapas.inserir')&&<><button className="app-button" onClick={()=>setImporting(true)}><Upload/>Importar</button><AddButton onClick={openNewStage}>Nova etapa</AddButton></>}</div>}/>
    {error&&<ErrorNotice message={error.message}/>}
    {!parents.length?<EmptyState title="Cronograma vazio" description="Cadastre a primeira etapa da execução da obra." action={can('etapas.inserir')?<AddButton onClick={openNewStage}>Cadastrar etapa</AddButton>:undefined}/>:<div className="crud-table-frame schedule-grid"><div className="table-summary schedule-table-toolbar"><div><strong>{data.totalRegistros}</strong> itens do cronograma <span>({data.total} etapas · {data.totalRegistros-data.total} subitens)</span></div><label className="schedule-planned-toggle"><input type="checkbox" checked={showPlanned} onChange={event=>setShowPlanned(event.target.checked)}/><span>Mostrar previsto</span></label></div><table className={`data-table schedule-parent-table ${showPlanned?'show-planned':''}`}><thead><tr><SortableHeader<ScheduleStage> label="Ordem" column="ordem" activeColumn={stagesSort.sort.key} direction={stagesSort.sort.direction} onSort={stagesSort.toggle}/><SortableHeader<ScheduleStage> label="Etapa" column="nome" activeColumn={stagesSort.sort.key} direction={stagesSort.sort.direction} onSort={stagesSort.toggle}/>{showPlanned&&<><SortableHeader<ScheduleStage> label="Início Previsto" column="data_inicio_previsto" activeColumn={stagesSort.sort.key} direction={stagesSort.sort.direction} onSort={stagesSort.toggle}/><SortableHeader<ScheduleStage> label="Fim Previsto" column="data_fim_previsto" activeColumn={stagesSort.sort.key} direction={stagesSort.sort.direction} onSort={stagesSort.toggle}/><SortableHeader<ScheduleStage> label="Valor Orçado" column="valor_previsto" className="money-column" activeColumn={stagesSort.sort.key} direction={stagesSort.sort.direction} onSort={stagesSort.toggle}/></>}<SortableHeader<ScheduleStage> label="Início Real" column="data_inicio" activeColumn={stagesSort.sort.key} direction={stagesSort.sort.direction} onSort={stagesSort.toggle}/><SortableHeader<ScheduleStage> label="Fim Real" column="data_fim" activeColumn={stagesSort.sort.key} direction={stagesSort.sort.direction} onSort={stagesSort.toggle}/><SortableHeader<ScheduleStage> label="Valor Pago" column="valor_pago" className="money-column" activeColumn={stagesSort.sort.key} direction={stagesSort.sort.direction} onSort={stagesSort.toggle}/><th>A&#199;&#213;ES</th></tr></thead><tbody>{stagesSort.sorted.map((stage,index)=><ScheduleRows key={stage.id} stage={stage} color={index%8} showPlanned={showPlanned} expanded={expanded.has(stage.id)} canInsert={can('etapas.inserir')} canUpdate={can('etapas.atualizar')} canDelete={can('etapas.excluir')} onToggle={()=>toggle(stage.id)} onAdd={()=>openNewChild(stage.id)} onEdit={openEdit} onDelete={(item)=>confirm(item.parent_id?`Excluir o subitem ${item.nome}?`:`Excluir a etapa ${item.nome} e todos os seus subitens?`)&&remove.mutate(item.id)}/>)}</tbody></table></div>}
    {editing&&<div className="dialog-backdrop"><section className="dialog"><header><div><small>CRONOGRAMA</small><h2>{editing==='new'?(isChild?'Novo subitem':'Nova etapa'):(isChild?'Editar subitem':'Editar etapa')}</h2></div><button onClick={closeEditor}><X/></button></header><form onSubmit={submit}>{save.error&&<ErrorNotice message={save.error.message}/>} {isChild&&<label className="field span-2"><span>Etapa pai</span><select value={newParentId||''} onChange={event=>setNewParentId(Number(event.target.value))} disabled={editing!=='new'}>{parents.map(parent=><option value={parent.id} key={parent.id}>{parent.ordem} · {parent.nome}</option>)}</select></label>}<label className="field span-2"><span>{isChild?'Descrição':'Etapa'}</span><input name="nome" required defaultValue={editing==='new'?'':editing.nome}/></label>{!isChild&&<label className="field span-2"><span>Descrição</span><textarea name="descricao" rows={3} defaultValue={editing==='new'?'':editing.descricao||''}/></label>}<label className="field"><span>Data de início Previsto</span><input name="data_inicio_previsto" type="date" defaultValue={editing==='new'?'':editing.data_inicio_previsto?.slice(0,10)}/></label><label className="field"><span>Data de Fim Previsto</span><input name="data_fim_previsto" type="date" defaultValue={editing==='new'?'':editing.data_fim_previsto?.slice(0,10)}/></label><label className="field"><span>Data de Início</span><input name="data_inicio" type="date" defaultValue={editing==='new'?'':editing.data_inicio?.slice(0,10)}/></label><label className="field"><span>Data de Fim</span><input name="data_fim" type="date" defaultValue={editing==='new'?'':editing.data_fim?.slice(0,10)}/></label><label className="field"><span>Valor Orçado</span><input name="valor_previsto" type="number" step="0.01" min="0" defaultValue={editing==='new'?0:editing.valor_previsto}/></label><label className="field compact"><span>Ordem</span><input name="ordem" type="number" min="0" defaultValue={editing==='new'?0:editing.ordem}/></label><footer className="form-actions span-2"><button type="button" className="app-button" onClick={closeEditor}>Cancelar</button><button className="app-button primary" disabled={save.isPending}>{save.isPending?'Salvando…':`Salvar ${isChild?'subitem':'etapa'}`}</button></footer></form></section></div>}
    {importing&&<ImportDialog endpoint={endpoint} entityName="cronograma" onClose={()=>setImporting(false)} onComplete={()=>{setImporting(false);void client.invalidateQueries({queryKey:['etapas',projetoId]})}}/>}
  </div>
}

function ScheduleRows({stage,color,showPlanned,expanded,canInsert,canUpdate,canDelete,onToggle,onAdd,onEdit,onDelete}:{stage:ScheduleStage;color:number;showPlanned:boolean;expanded:boolean;canInsert:boolean;canUpdate:boolean;canDelete:boolean;onToggle:()=>void;onAdd:()=>void;onEdit:(item:ScheduleItem)=>void;onDelete:(item:ScheduleItem)=>void}){
  return <><tr className={`schedule-parent-row stage-color-${color}`} onClick={onToggle}><td><strong>{stage.ordem}</strong></td><td><button className="schedule-expand" aria-label={expanded?'Contrair etapa':'Expandir etapa'}>{expanded?<ChevronDown/>:<ChevronRight/>}</button><div><strong>{formatStageLabel(stage)}</strong>{stage.descricao&&<small>{stage.descricao}</small>}</div></td>{showPlanned&&<><td>{formatDate(stage.data_inicio_previsto)}</td><td>{formatDate(stage.data_fim_previsto)}</td><td className="money-column"><strong>{formatMoney(stage.valor_previsto)}</strong></td></>}<td>{formatDate(stage.data_inicio)}</td><td>{formatDate(stage.data_fim)}</td><td className="money-column"><strong>{formatMoney(stage.valor_pago)}</strong></td><td className="row-actions">{canInsert&&<button onClick={event=>{event.stopPropagation();onAdd()}} title="Adicionar subitem" aria-label="Adicionar subitem"><Plus/></button>}{canUpdate&&<button onClick={event=>{event.stopPropagation();onEdit(stage)}} aria-label="Editar etapa"><Pencil/></button>}{canDelete&&<button className="danger" onClick={event=>{event.stopPropagation();onDelete(stage)}} aria-label="Excluir etapa"><Trash2/></button>}</td></tr>{expanded&&<tr className="schedule-children-row"><td colSpan={showPlanned?9:6}><div className="schedule-children">{stage.subitens.length?<table className={`schedule-child-table ${showPlanned?'show-planned':''}`}><thead><tr><th>Ordem</th><th>Descrição</th>{showPlanned&&<><th>Início Previsto</th><th>Fim Previsto</th><th className="money-column">Valor Orçado</th></>}<th>Início Real</th><th>Fim Real</th><th className="money-column">Valor Pago</th><th>A&#199;&#213;ES</th></tr></thead><tbody>{[...stage.subitens].sort((a,b)=>a.ordem-b.ordem||a.id-b.id).map(child=><tr key={child.id}><td>{child.ordem}</td><td><strong>{child.nome}</strong></td>{showPlanned&&<><td>{formatDate(child.data_inicio_previsto)}</td><td>{formatDate(child.data_fim_previsto)}</td><td className="money-column">{formatMoney(child.valor_previsto)}</td></>}<td>{formatDate(child.data_inicio)}</td><td>{formatDate(child.data_fim)}</td><td className="money-column">{formatMoney(child.valor_pago)}</td><td className="row-actions">{canUpdate&&<button onClick={()=>onEdit(child)} aria-label="Editar subitem"><Pencil/></button>}{canDelete&&<button className="danger" onClick={()=>onDelete(child)} aria-label="Excluir subitem"><Trash2/></button>}</td></tr>)}</tbody></table>:<p className="schedule-empty-children">Nenhum subitem cadastrado nesta etapa.</p>}{canInsert&&<button className="schedule-add-child" type="button" onClick={onAdd}><Plus/>Adicionar subitem</button>}</div></td></tr>}</>
}
